### ISSUE TITLE
dateWithString:format: returning nil

### ISSUE THREAD

**Issue by evanrobertson** [MatthewYork/DateTools#113]
If I try and create a date from a format string every so often it will return nil, whilst using `dateWithYear:month:day:` with the same parameters will return the correct value. 

Unsure if this is a bug with the library, looking at the method it seems like it might be something I am doing wrong, however I would like to know what I may be doing wrong.

```
NSNumber *year = @(2015);
NSNumber *month = @(10);

NSString *dateString = [NSString stringWithFormat:@"01/%@/%@", month, year];
NSDate *key = [NSDate dateWithString:dateString formatString:@"dd/MM/yyyy"]; // Sometimes nil
NSDate *key2 = [NSDate dateWithYear:year month:month day:1]; // Always successful
```

**Comment by evanrobertson** [comment]
To answer my own question,
[NSDateFormatter is thread-unsafe](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/Multithreading/ThreadSafetySummary/ThreadSafetySummary.html)

As is NSCalendar, so I guess my next question is about thread safety in DateTools, can we make improvements to allow us to work with dates on multiple threads?

**Comment by kubatru** [comment]
Discovered that the system that uses 12h time returns nil for ```dateWithString:format:```, otherwise it works correctly.
