### ISSUE TITLE
Implement startOf and endOf

### ISSUE THREAD

**Issue by revolter** [MatthewYork/DateTools#132]
[Moment.js][1] has two great functions for [Start of Time][2] and [End of Time][3] implemented [here][4]. I tried translating it to Objective-C but it doesn't work quite well, especially for the start of the week. And I don't have time to write tests too. Here is my draft:

	- (NSDate *)startOf:(NSCalendarUnit)calendarUnit {

		static NSCalendar *calendar = nil;
		static dispatch_once_t onceToken;

		dispatch_once(&onceToken, ^{
			calendar = [[NSCalendar alloc] initWithCalendarIdentifier:NSCalendarIdentifierGregorian];

			calendar.firstWeekday = 2;
			calendar.minimumDaysInFirstWeek = 4;
		});

		NSDateComponents *dateComponents = [calendar components:ATIAllCalendarUnitFlags fromDate:self];

		switch (calendarUnit) {
			case NSCalendarUnitYear:
				dateComponents.month = 0;

				/* falls through */
			case NSCalendarUnitQuarter:
			case NSCalendarUnitMonth:
				dateComponents.day = 1;

				/* falls through */
			case NSCalendarUnitWeekday:
			case NSCalendarUnitWeekOfYear:
			case NSCalendarUnitDay:
				dateComponents.hour = 0;

				/* falls through */
			case NSCalendarUnitHour:
				dateComponents.minute = 0;

				/* falls through */
			case NSCalendarUnitMinute:
				dateComponents.second = 0;

				/* falls through */
			default:
				break;
		}

		// weeks are a special case
		if (calendarUnit == NSCalendarUnitWeekday) {
			dateComponents.weekday = 0;
		}
		if (calendarUnit == NSCalendarUnitWeekOfYear) {
			dateComponents.weekOfYear = 1;
		}

		// quarters are also special
		if (calendarUnit == NSCalendarUnitQuarter) {
			dateComponents.month = floor(dateComponents.month / 3.0) * 3;
		}

		return [calendar dateFromComponents:dateComponents];
	}

Hope someone manages to finish and make it work.

  [1]: http://momentjs.com
  [2]: http://momentjs.com/docs/#/manipulating/start-of
  [3]: http://momentjs.com/docs/#/manipulating/end-of
  [4]: https://github.com/moment/moment/blob/cd49a734350193a244c596a02167221cbca2c06f/src/lib/moment/start-end-of.js

**Comment by kh0r** [comment]
You can use NSCalendars rangeOfUnit function for this:
https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSCalendar_Class/#//apple_ref/occ/instm/NSCalendar/rangeOfUnit:startDate:interval:forDate:

**Comment by kh0r** [comment]
Better late than never ;)

**Comment by MatthewYork** [comment]
We will probably shorthand this in our Swift release. Nice find.

@graysonwebster see [here](http://momentjs.com/docs/#/manipulating/start-of/)

**Comment by revolter** [comment]
So it's ok to close this now?

**Comment by MatthewYork** [comment]
Sounds good to me. Thanks!
