### ISSUE TITLE
Cannot prune localizations

### ISSUE THREAD

**Issue by philipengberg** [MatthewYork/DateTools#140]
We're using `cocoapods-prune-localizations` in order to prune unsupported localizations from third party libraries. However, when we do this for DateTools, we get runtime errors here:

``` objc
- (NSString *) logicLocalizedStringFromFormat:(NSString *)format withValue:(NSInteger)value{
    NSString * localeFormat = [NSString stringWithFormat:format, [self getLocaleFormatUnderscoresWithValue:value]];
    return [NSString stringWithFormat:DateToolsLocalizedStrings(localeFormat), value]; // <-- Here
}
```

saying that 

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', 
reason: '*** -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument'
```

However, if we add the project manually and **manually** remove the unneeded `*.lproj` files, everything works fine.

We would of course prefer to use DateTools as a pod instead od integrating it directly into our project.

Hope you will have the time to fix this issue.

**Comment by pomarec** [comment]
i had something similar, did you try to update cocoapods to the --pre version and reinstall the pod ?

**Comment by WedgeSparda** [comment]
I'm getting this same error. 
Added the bundle, still crashing. 
Reinstall the pod, still crashing.

Any solution despite installing the library manually?

**Comment by MatthewYork** [comment]
This was recently pointed out by @philipengberg as an issue in our updated DateToolsSwift version in issue #199 . I am closing this issue since DateToolsSwift is now the supported pod going forward. All updates will be posted there. Thanks!
