### ISSUE TITLE
Use self.class on constructors so it can be inhertable

### ISSUE THREAD

**Issue by BadChoice** [MatthewYork/DateTools#160]
I want to create an `Event` class that inherts from `DTTimePeriod` but I can't use its constructors since they return a `DTTimePeriod` object instead a `self.class` one

Basically is replacing:

```
    return [[DTTimePeriod alloc] initWithStartDate:date endDate:[DTTimePeriod dateWithAddedTime:size amount:amount baseDate:date]];
```

by 

```
    return [[self.class alloc] initWithStartDate:date endDate:[DTTimePeriod dateWithAddedTime:size amount:amount baseDate:date]];
```

**Comment by MatthewYork** [comment]
Fixed in commit 682c271f9189c7320aedd2f57aeb27d1ed1fba9a
