### ISSUE TITLE
Unable to use the swift branch in Cocopods

### ISSUE THREAD

**Issue by dianambb** [MatthewYork/DateTools#163]
With Swift 3.0 Date is a native type. Bringing in the Objective-C framework causes a build error because of this. I am trying to use the swift branch and added this to the pod file:

`pod 'DateTools', :git => 'https://github.com/MatthewYork/DateTools.git' :branch => 'swift'`

When I run pod update I see this error:

```
Analyzing dependencies
Pre-downloading: `DateTools` from `https://github.com/MatthewYork/DateTools.git`, branch `swift`
[!] Unable to find a specification for 'DateTools'.

[!] Unable to load a podspec from `DateTools.podspec`, skipping:

Pod::DSLError
```

**Comment by MatthewYork** [comment]
We are very close to finishing up a full Swift 3.0 launch (see the swift branch). Until then, you may consider using Swift 2.3

**Comment by dianambb** [comment]
Thanks. It looks like PR #162 will unblock me.

**Comment by MatthewYork** [comment]
PR 162 is merged. Please let me know if you are unblocked.

**Comment by dianambb** [comment]
Thanks this works for me now!
