### ISSUE TITLE
Methods removed from Swift branch (isLaterThan, isSameDay, etc)

### ISSUE THREAD

**Issue by dmorrow** [MatthewYork/DateTools#165]
While migrating from the ObjC branch to the Swift branch, it seems many convenience methods have been removed from NSDate+Tools.
What is the recommended pattern to handle these types of comparisons?

**Comment by graysonwebster** [comment]
A lot of methods have been renamed to be more "swifty." The features you're looking for are in the Date+Comparators.swift file. Check out the equals, greater, and less methods.
