### ISSUE TITLE
Format and localise date as time duration

### ISSUE THREAD

**Issue by k06a** [MatthewYork/DateTools#166]
I wanna easily show ages of pets/babies like: `20 days`, `3 months`, `1 year 2 months`, `5 years`

I found nothing similar in localisations bundle 😞

**Comment by graysonwebster** [comment]
DateTools has an extension to the Date class that does exactly this, called chunkBetween.
```
let formatter = DateFormatter()
formatter.dateFormat = "yyyy MM dd HH:mm:ss.SSS"
let birthday = formatter.date(from: "2015 11 24 14:50:12.000")!
let age = birthday.chunkBetween(date: Date())
```
The age variable will have a chunk of time with year, month, day, hour, minute, and second components (note that we do not use weeks in the chunk to avoid confusion). So if you just wanted the age in years, you could then say: `age.years`.
The chunk is calculated exactly as you'd say it in real life, always converting up when a lower unit equals 1 of the unit above it. The above example returned `TimeChunk(seconds: 37, minutes: 9, hours: 0, days: 4, weeks: 0, months: 10, years: 0)`when I ran it just now.
Passing a future date returns a TimeChunk with all positive components and passing a date in the past returns one with all negative components.

**Comment by k06a** [comment]
@graysonwebster are you sure? Can't find any code/documentation for this methods

<img width="1033" alt="2016-09-29 22 02 24" src="https://cloud.githubusercontent.com/assets/702124/18968139/83e5a43e-8690-11e6-905f-949e6db7bb94.png">

**Comment by k06a** [comment]
Whole GitHub contains single result for `chunkBetween`:

<img width="1039" alt="2016-09-29 22 05 16" src="https://cloud.githubusercontent.com/assets/702124/18968246/e9cab3f2-8690-11e6-836c-423ab94c27fb.png">

**Comment by MatthewYork** [comment]
Pretty sure it only takes master branch for searching. We haven't merged the swift branch into master yet, so that would explain why it doesn't show up. 

Here is the reference to the code you are looking for:
https://github.com/MatthewYork/DateTools/blob/swift/DateTools/Date%2BComparators.swift
