### ISSUE TITLE
use method'formattedDateWithFormat' in December is wrong

### ISSUE THREAD

**Issue by Rita5969** [MatthewYork/DateTools#167]
when I user formattedDateWithFormat,the result has append 1 year,am i wrong?
<img width="696" alt="12month" src="https://cloud.githubusercontent.com/assets/3962170/18897828/e5027e7c-855f-11e6-96a6-a6cf976ee37f.png">

**Comment by kientux** [comment]
@Rita5969 why did you close this issue? I had the same issue but can't find a way to fix it (but I think this is a bug from the library).
