### ISSUE TITLE
Why are beginning and end optional in TimePeriodProtocol?

### ISSUE THREAD

**Issue by csimmons0** [MatthewYork/DateTools#168]
I'm switching from 1.7 to the Swift branch, and I'm curious as to what the rationale for making _beginning_ and _end_ optional in TimePeriodProtocol was. The properties' counterparts in 1.7, DTTimePeriod.startDate and DTTimePeriod.endDate, weren't optional, or they were implicitly unwrapped if they were. Having to unwrap them with the new code is a bit of an inconvenience.

**Comment by graysonwebster** [comment]
The main reason for making those optional was to allow some way to describe a time period that has an indefinite beginning or end date. It's a little annoying, but it buys us this feature.

**Comment by csimmons0** [comment]
Fair enough; thanks for the explanation.
