### ISSUE TITLE
Swift branch multi-language not work

### ISSUE THREAD

**Issue by huangboju** [MatthewYork/DateTools#169]

**Comment by graysonwebster** [comment]
We're looking into it right now. We believe it has to do with the access to the bundle in the module. The previous access procedures no longer work.

**Comment by huangboju** [comment]
@graysonwebster 
I tried to solve, but did not succeed
https://github.com/zhangao0086/DKImagePickerController
Multilanguage of this library is also by bundle

**Comment by MatthewYork** [comment]
DateToolsSwift is now the preferred cocoapod and Swift 3 compatible version (as per documentation). Localizations have been confirmed to work as of version 2.0.2. Thanks for using DateTools!
