### ISSUE TITLE
Problem with TimeChunk (Swift version)

### ISSUE THREAD

**Issue by igormatyushkin014** [MatthewYork/DateTools#170]
This problem happens when I use Swift version of `DateTools` library. I need to use `TimeChunk` to subtract one `Date` from another. This is example of code:

```swift
var chunk: TimeChunk
chunk.days = 2

let twoDaysAgo = Date().subtract(chunk)
```

Compiler shows the error: `days` is inaccessible due to `internal` protection level.

Probably I'm doing something wrong. How should I use `TimeChunk` for adding/subtracting time intervals in Swift version?

**Comment by graysonwebster** [comment]
The best way to do this would be:
`let twoDaysAgo = Date() - 2.days`
