### ISSUE TITLE
Support for Swift Package Manager?

### ISSUE THREAD

**Issue by UberJason** [MatthewYork/DateTools#171]
I'm a long time fan of DateTools and very excited to see you're working toward a Swift release! I'm wondering if there are any plans to support Swift Package Manager (SwiftPM) in the future? DateTools in Server-side Swift via SwiftPM would be amazing. Since DateTools would, hypothetically, be dependent only on Foundation and not UIKit or AppKit or anything like that, and Foundation has been ported to Linux with Swift 3, it seems like a lot of the building blocks are in place for the migration already.

**Comment by MatthewYork** [comment]
Thanks for using DateTools! We definitely will support the swift PM. If you feel like you can help to get that up and running, feel free to issue a pull request!  There is still much to do.
