### ISSUE TITLE
swift version of README

### ISSUE THREAD

**Issue by Busta117** [MatthewYork/DateTools#175]
would be nice if someone translate the README.md file to swift in the swift branch of course.... 

this can be part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) with a label `Hacktoberfest`

**Comment by horaciogarza** [comment]
I'll do it

**Comment by graysonwebster** [comment]
[README.md.zip](https://github.com/MatthewYork/DateTools/files/544555/README.md.zip)

Thanks for the help! We've already started on it, but there's still more to do. In the attached readme, only the intro and the section on TimeChunks through the subsection on formatted date strings (lines 83-282) have been edited. You can use the attached readme as your starting point.

**Comment by horaciogarza** [comment]
@graysonwebster sure, thx

**Comment by MatthewYork** [comment]
Documentation could still use a hand.. But I will be closing this for now and work with @graysonwebster directly.
