### ISSUE TITLE
swift version in cocoapods 

### ISSUE THREAD

**Issue by Busta117** [MatthewYork/DateTools#176]
would be great if we can install this pod directly doing `pod 'DateToolsSwfit'` or something similar rather add the branch name, or i don't know if it's possible that cocoapods get automatically the swift version if we are developing over swift

this can be part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) with a label `Hacktoberfest`

**Comment by MatthewYork** [comment]
Agreed. We are close! Leaving package management stuff to the end since the API itself isn't 100% stable yet. We are still reviewing method signatures, etc, so we thought it prudent to wait.

But we will be looking at this very soon.

**Comment by MatthewYork** [comment]
DateToolsSwift pod is now available via cocoapods. Current version is 2.0.2. Thanks for using DateTools!
