### ISSUE TITLE
Swift 3 Date

### ISSUE THREAD

**Issue by oleynikd** [MatthewYork/DateTools#181]
Hi,

Please help!
How to use `DateTools` in Swift3 project with [`Date`](https://developer.apple.com/reference/foundation/date) class? 

Thanks

**Comment by fjcaetano** [comment]
A workaround is by casting your date to NSDate:

``` swift
(date as NSDate).timeAgoSinceNow()
```

**Comment by antonyalkmim** [comment]
You can use pod from  [`swift`](https://github.com/MatthewYork/DateTools/tree/swift) branch
```
pod 'DateTools', :git => 'https://github.com/MatthewYork/DateTools', :branch => 'swift'
```
and use like this
```swift
Date().timeAgoSinceNow 
```

**Comment by basilmariano** [comment]
is it recommendable to use Beta for the project or we need t use the branch master for development?
I'm using Swift 3
thanks

**Comment by MatthewYork** [comment]
DateToolsSwift version 2.0.2 is available for Swift 3. This is now the preferred pod as per updated documentation. Thanks!

**Comment by marmoy** [comment]
Just a correction to the comment by @antonyalkmim. If you want to use DateTools with Swift, you should put 

    pod 'DateToolsSwift', :git => 'https://github.com/MatthewYork/DateTools', :branch => 'swift'

not 

    pod 'DateTools', :git => 'https://github.com/MatthewYork/DateTools', :branch => 'swift'

in your podfile
