### ISSUE TITLE
TimeChunk initializer not publicly available

### ISSUE THREAD

**Issue by reabbotted** [MatthewYork/DateTools#183]
In the Swift branch in the Date+Manipulations.swift file, I'd like to use the 'subtract' and 'add' functions:

func add(_ timeChunk: TimeChunk) -> Date
func subtract(_ timeChunk: TimeChunk) -> Date

The required parameter is the TimeChunk. However, the initializers for TimeChunk are not available outside of the package, so when the project is installed with CocoaPods, I'm unable to initialize TimeChunk. I believe 

TimeChunk.swift:

init()
init(seconds: Int, minutes: Int, hours: Int, days: Int, weeks: Int, months: Int, years: Int)

should be:

public init() 
public init(seconds: Int, minutes: Int, hours: Int, days: Int, weeks: Int, months: Int, years: Int)

**Comment by MatthewYork** [comment]
Thank you. Looking into it now!

**Comment by graysonwebster** [comment]
Fixed in commit c15c043.

**Comment by reabbotted** [comment]
Great work. Thanks for taking the time with this project.
