### ISSUE TITLE
Why the Swift version did not use a new repository？

### ISSUE THREAD

**Issue by Huang-Libo** [MatthewYork/DateTools#185]
In general，an Obj-C repository immigration to swift version would use a new repository, why _DateTools_ decide to use the same repository?

**Comment by richardtop** [comment]
@Huang-Libo Now it does, you can install Swift version using `pod 'DateToolsSwift'`

**Comment by Huang-Libo** [comment]
@richardtop Now I can see that  _DateTools_ use different branch to develop ObjC and Swift version, also very good!
