### ISSUE TITLE
localizations is not working

### ISSUE THREAD

**Issue by IOSAppDev5** [MatthewYork/DateTools#189]
Hi 

When i tired to change the phone language settings and see the below line code  

"date.timeAgoSinceNow" always giving in english code ... and when i see the code base .

I am excepting to be localized which ever language i selected.

Suppose.

english 

15 years ago

for french.
Il y a 15 ans

/* No comment provided by engineer. */
"%d years ago" = "Il y a %d ans";

what ever defined in localize file

please help me to understand the flow.

**Comment by dianambb** [comment]
I am having the same issue

**Comment by MatthewYork** [comment]
Hello all, 

I have verified for version 2.0.2 in the test project and via cocoapods that the localizations are working. Please be advised that localizations will only appear if they are enumerated your info.plist as a supported language. Thanks for using DateTools!
