### ISSUE TITLE
(watchOS 3.1) is not compatible with DateTools (2.0.0)

### ISSUE THREAD

**Issue by malkabani** [MatthewYork/DateTools#197]
Hi

I have a project with watch app.

when try to make pod update, issue appear with this message

The platform of the target `birds-eye-watchapp Extension` (watchOS 3.1) is not compatible with `DateTools (2.0.0)`, which does not support `watchos`.

can you help me?

Thanks

**Comment by MatthewYork** [comment]
Watch OS support is available in cocoapod version 2.0.2! Thanks for using DateTools!
