### ISSUE TITLE
Code doesn't compile

### ISSUE THREAD

**Issue by grosch** [MatthewYork/DateTools#261]
https://github.com/MatthewYork/DateTools/blob/76ba8bafccb0b28d9af74a8f525a74b5276ed693/DateToolsSwift/DateTools/TimePeriodGroup.swift#L105

Compiling with the latest xcode returns an error here about not being able to convert to AnySequence.

**Comment by tokuduz** [comment]
Hi, please read an issue below urs.

Here is the link
https://github.com/MatthewYork/DateTools/issues/260

**Comment by grosch** [comment]
I was getting DateTools from CalendarKit so I thought I had the most recent.  I discovered that my CocoaPods repository wasn't actually updating.
