### ISSUE TITLE
Unit method from Date+Components extension not working

### ISSUE THREAD

**Issue by zvjerka24** [MatthewYork/DateTools#275]
If you try to get number of days in month, response is nil

example:
Date().unit(of: Calendar.Component.day, in: Calendar.Component.month)

**Comment by MatthewYork** [comment]
The unit tests began to fail because it appears the calendar component hashes are no longer reliable for this calculation.  I am deprecating the unit function and removing unit tests until it may be re-implemented without relying on hashing.
