### ISSUE TITLE
How to use with SwiftPM

### ISSUE THREAD

**Issue by bryan1anderson** [MatthewYork/DateTools#286]
I cannot figure this out at all. I'm needing this as my last push to use SwiftPM to house my data layer of my app. Please help
`.package(url: "https://github.com/MatthewYork/DateTools", from: "4.0.0")`
Does not work

**Comment by multinerd** [comment]
You should really search before posting. 

Theres a pending pull request (#285) that adds support for SwiftPM, but in case you haven't noticed, this repo has not been updated since March 2018.

**Comment by 3a4oT** [comment]
you can use [objc version](https://github.com/3a4oT/DateToolsObjC) of it. Just added SPM support.

```
.package(url: "https://github.com/3a4oT/DateToolsObjC", .upToNextMajor(from: "1.0.4"))

```

**Comment by MatthewYork** [comment]
I'm back! (see #285  for details) 

If anyone will add support for SwiftPM without method refactors branched from my newest release, i would be happy to merge it in.

**Comment by MatthewYork** [comment]
I'm going to close this as a duplicate. Rest assured I will merge SwiftPM support as soon as someone creates a PR from the new release.
