### ISSUE TITLE
Compare time instance only

### ISSUE THREAD

**Issue by ArtworkAD** [MatthewYork/DateTools#42]
In my application only the time part of a date matters. Is it possible to compare dates only considering the time? Currently I am doing this by calculating minutes from the time part. This produces a lot of boilerplate code.

In JAVA: http://joda-time.sourceforge.net/api-release/org/joda/time/DateTimeComparator.html#getTimeOnlyInstance()

**Comment by MatthewYork** [comment]
One way to compare the time (without extending the API) is to compare the date's components.

if (date1.hour == date2.hour && date1.minute == date2.minute ...etc)

It would be a nice feature, however. I will look at working this in, unless you would like to make a pull request.
