### ISSUE TITLE
isEqual instead of isEqualToString? (Russian and Ukrainian locales)

### ISSUE THREAD

**Issue by lucaji** [MatthewYork/DateTools#46]
Hi, I might be wrong because Im pretty new to objc, but in NSDate+DateTools.m in the method getLocaleFormatUnderscoresWithValue there are two NSString compared using isEqual.

// Russian (ru) and Ukrainian (uk)
    if([localeCode isEqual:@"ru"] || [localeCode isEqual:@"uk"]) {

should be replaced with

// Russian (ru) and Ukrainian (uk)
    if([localeCode isEqualToString:@"ru"] || [localeCode isEqualToString:@"uk"]) {

Cheers, Luca

**Comment by MatthewYork** [comment]
I believe you are correct. <code>isEqual</code> should compare top-level pointers, not string equality.

I will get this worked into the next release. Thanks!

**Comment by MatthewYork** [comment]
Fixed in commit: 77c4955d23094ebad6268579b94f90d8a4a953c7

**Comment by carllindberg** [comment]
Just a comment -- isEqual: simply calls -isEqualToString:, so the functionality is the same.  Calling isEqualToString: directly is very slightly better performance, and has a typed argument so coding errors will be picked up better, so it's preferred but not absolutely necessary.
