### ISSUE TITLE
timeAgoSinceDate returns "yesterday" when it should be "day before yesterday"

### ISSUE THREAD

**Issue by ebekebe** [MatthewYork/DateTools#47]
I found that the timeAgoSinceDate method does not return the correct day. For  [yesterday22h timeAgoSinceDate:tomorrow1h] I expected something like "the day before yesterday", but instead "yesterday" was returned, which is wrong.

I use German localization, so the actual example looks like this:

    NSDateFormatter *dateFormat = [[NSDateFormatter alloc] init];
    [dateFormat setDateFormat:@"yyyy-MM-dd HH:mm:ss"];

    NSDate* yesterday2h = [dateFormat dateFromString:@"2000-01-31 02:00:00"];
    NSDate* tomorrow1h = [dateFormat dateFromString:@"2000-02-02 01:00:00"];
    
    XCTAssertNotEqualObjects([yesterday2h timeAgoSinceDate:tomorrow1h], @"Gestern");

I use DateTools 1.4.3.

**Comment by marcferna** [comment]
+1

**Comment by mythodeia** [comment]
does this happen with the latest commit?

**Comment by marcferna** [comment]
I'm using the latest pod version. I'm working on a fix now

**Comment by marcferna** [comment]
You can check my fix: https://github.com/MatthewYork/DateTools/pull/74

**Comment by mythodeia** [comment]
@marcferna does this fix apply to 
```- (NSString *)shortTimeAgoSinceDate:(NSDate *)date{``` 
as well?

**Comment by marcferna** [comment]
I forgot about `shortTimeAgoSinceDate` but now it includes it.

**Comment by mythodeia** [comment]
:+1:
