### ISSUE TITLE
Compare two times?

### ISSUE THREAD

**Issue by malcommac** [MatthewYork/DateTools#51]
Is there a way to compare two time discarding the date component?
Ie: 15:00 is earlier than 17:00.
(I could create two NSDate of the same day with these two hours but it's the best way to use DateTools?)

**Comment by MatthewYork** [comment]
So, the only way to do this at the moment is to compare all the components (to the lowest degree of certainty you care about) individually. So, you would compare 

if (date1.hour == date2.hour && date1.minute == date2.minute ....)

I think there should be a method for short handing what you are talking about, so I may work it into the next release.
