### ISSUE TITLE
Crash when using with cocoapods

### ISSUE THREAD

**Issue by tonyxiao** [MatthewYork/DateTools#56]
Crashes on the following line

```
NSLocalizedStringFromTableInBundle(key, @"DateTools", [NSBundle bundleWithPath:[[[NSBundle mainBundle] resourcePath] stringByAppendingPathComponent:@"DateTools.bundle"]], nil)
```

The new cocoapods now uses swift modules and embedded frameworks, so DateTools.bundle is no longer at its old location, thus causing a crash due to nil being returned.

**Comment by summerblue** [comment]
Got the same problem too.

**Comment by summerblue** [comment]
My quick fix is: 
1. Find the `DateTools.bundle` file at the `Pods/DateTools/DateTools/DateTools.bundle`;
2. Drag the `DateTools.bundle` file into anywhere at the xcode project, import using relative file path.

**Comment by lewis-smith** [comment]
+1 for this issue and @summerblue 's work around.

**Comment by tonyxiao** [comment]
Another workaround is the following, though I probably like @summerblue's workaround better

```
        if target.name == 'Pods-DateTools'
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'DateToolsLocalizedStrings(key)=key'
            end
        end
```

**Comment by Fl0p** [comment]
:+1: for this

**Comment by mergesort** [comment]
@MatthewYork Can these bundle fixes be merged in? I'm going to have to remove DateTools before my next app build if I can't get it to compile.

**Comment by mergesort** [comment]
Should be fixed now. https://github.com/MatthewYork/DateTools/pull/60#issuecomment-94286205

**Comment by MatthewYork** [comment]
Fixed as of #84

**Comment by davetroy** [comment]
Seeing this again now with Cocoapods 1.0; have not identified a workaround yet.

**Comment by ricardochavarria** [comment]
Seeing this also with CocoaPods 1.01. Anyone found a solution?

**Comment by ardarda** [comment]
Any solutions so far? Using CocoaPods 1.01

**Comment by ardarda** [comment]
NSLocalizedStringFromTableInBundle(key, @"DateTools", [NSBundle bundleWithPath:[[[NSBundle bundleForClass:[DTError class]] resourcePath] stringByAppendingPathComponent:@"DateTools.bundle"]], nil) 

should do the trick, but still can not find the bundle, I checked the folder structure everything seems fine, confused actually.
