### ISSUE TITLE
Start of week

### ISSUE THREAD

**Issue by verbeeckjan** [MatthewYork/DateTools#62]
Is there an easy way to find the start of the week? Or is there some detailed documentation available somewhere?

If there is no easy way to get the start of the week this might be a nice-to-have feature.

Thanks in advance

**Comment by mythodeia** [comment]
something like this maybe?
```
- (NSDate *)firstDayOfWeek{
    BOOL weekStartMonday = YES;
    NSCalendar *calendar = [[self class] implicitCalendar];
    NSDateComponents *weekdayComponents = [calendar components:NSCalendarUnitWeekday fromDate:self];

    NSInteger weekdayoffset1 = (weekStartMonday) ? 2 : 1;

    NSDateComponents *componentsToSubtract  = [[NSDateComponents alloc] init];
    [componentsToSubtract setDay: (0 - ([weekdayComponents weekday] == 1 ? 8 : [weekdayComponents weekday])) + weekdayoffset1];

    NSDate *beginningOfWeek = [calendar dateByAddingComponents:componentsToSubtract toDate:self options:0];
    return beginningOfWeek;
}
```

**Comment by verbeeckjan** [comment]
Well ultimately I found that this method works for me (week starts on monday): 

+(NSDate*)getFirstDayOfTheWeek {
    NSDate *today = [[NSDate alloc] init];
    
    today =[today dateBySubtractingHours:today.hour];
    today =[today dateBySubtractingMinutes:today.minute];
    today =[today dateBySubtractingSeconds:today.second];
    
    return[today dateBySubtractingDays:(today.weekday + 5) % 7];
}
