### ISSUE TITLE
Missing resources with cocoapods use_frameworks! 

### ISSUE THREAD

**Issue by Fl0p** [MatthewYork/DateTools#67]
Related issue - https://github.com/CocoaPods/CocoaPods/issues/3226

https://github.com/MatthewYork/DateTools/blob/master/DateTools/NSDate%2BDateTools.h#L23-26

Should use [NSBundle bundleForClass:] to determinate correct resources location path

**Comment by blebaron** [comment]
Looks like this is a duplicate of #56. Which already has a pull request #60 with a fix ready to go.

**Comment by Fl0p** [comment]
@blebaron Yeap, exactly
:+1:
