### ISSUE TITLE
Support Cocoapods 0.36

### ISSUE THREAD

**Issue by valeriomazzeo** [MatthewYork/DateTools#69]
At the moment DateTools crashes when installed through version of cocoapods 0.36+

The main change is that now the resources bundle are not included into the main one, but they are inside the framework. You can find more information here: http://blog.cocoapods.org/CocoaPods-0.36/

> Caveats
One caveat about bundling resources is, that until now we had to embed all resources into the application bundle. The resources were referenced programmatically by [NSBundle mainBundle]. Pod authors were able to use mainBundle referencing to include resources the Pod brought into the app bundle. But with frameworks, you have to make sure that you reference them more specifically by getting a reference to your framework's bundle e.g.

Objective-C
` [NSBundle bundleForClass:<#ClassFromPodspec#>]`

Swift
`NSBundle(forClass: <#ClassFromPodspec#>)`

For DateTools the problem is in this macro:

`NSLocalizedStringFromTableInBundle(key, @"DateTools", [NSBundle bundleWithPath:[[[NSBundle mainBundle] resourcePath] stringByAppendingPathComponent:@"DateTools.bundle"]], nil)`
Which can't find the bundle and returns `nil` causing the crash.

A possible solution, even if probably not the more elegant is to replace the macro with:

`NSLocalizedStringFromTableInBundle(key, @"DateTools", [NSBundle bundleForClass:NSClassFromString(@"DTTimePeriod")], nil)`

**Comment by tualatrix** [comment]
I also meet this issue when using DateTools as framework. This line of code fixed this. Thanks.

**Comment by jlalvarez18** [comment]
+1

**Comment by MatthewYork** [comment]
Fixed in #84 and v1.6.0
