### ISSUE TITLE
isWeekend() returning true on a monday

### ISSUE THREAD

**Issue by phonghho** [MatthewYork/DateTools#75]
I have an NSDate object that is set to February 16, 2015 which is a Monday. When I use isWeekend() on it, it returns true. This is a swift app using a bridging header.

//Monday, Presidents Day
println(date)
2015-02-16 00:00:00 +0000

println(date.isWeekend())
true

**Comment by MatthewYork** [comment]
Ok, I think i have fixed this. Also, I specifically added that date and tested it. Good find!
