### ISSUE TITLE
timeAgo cause app crash

### ISSUE THREAD

**Issue by franklingu** [MatthewYork/DateTools#81]
for DateTools, I do think either clearly specify that even if cocoapods is used, we still need to drag the bundle over, or have this automatically solved...

**Comment by joeblau** [comment]
I'm noticing the same thing.

**Comment by jacksonh** [comment]
Probably a duplicate of this issue (which includes a workaround): https://github.com/MatthewYork/DateTools/issues/69

**Comment by joeblau** [comment]
Yep, this can be marked as a duplicate.  I had to drag the bundle with the localized strings into my project and everything was fixed.

**Comment by franklingu** [comment]
Can this be solved with shell script?

**Comment by franklingu** [comment]
Yes. This is duplicated. Can be closed therefore

**Comment by MatthewYork** [comment]
Closed

**Comment by MatthewYork** [comment]
Fixed in #84
