### ISSUE TITLE
Can we add a `isSameDay` method?

### ISSUE THREAD

**Issue by xilin** [MatthewYork/DateTools#86]
Currently we have two methods: `daysFrom` and `isToday`. `isToday` is very usefull when comparing with today. However `daysFrom` is not that usefull when checking if two dates is in the same day.
Can we add a `isSameDay` method? 
Thanks.

**Comment by kparent** [comment]
@xilin Take a look at my pull request and let me know if that works for you.

**Comment by xilin** [comment]
@kparent Thanks! I think it works well.

**Comment by MatthewYork** [comment]
I haven't forgotten about you guys. Just had a lot going on! I will get everything merged in as soon as I can.

-Matt

**Comment by MatthewYork** [comment]
merged! I will add some tests to round out the method soon.
