### ISSUE TITLE
What does just for kicks means

### ISSUE THREAD

**Issue by revolter** [MatthewYork/DateTools#93]
Is it a joke? Can I safely use formatting methods in production?

**Comment by MatthewYork** [comment]
Yes, "just for kicks", is an American English idiom describing something that is done in addition to the main objective, but was not absolutely necessarily. Basically, the formatting methods are for your convenience, and yes, they are safe for production.

**Comment by revolter** [comment]
So you're saying that formatting dates is not included in a date tools library? I thought it was an important part.

**Comment by MatthewYork** [comment]
No, they are included. The phrase is just used to imply they are “extra” methods meant to be a convenience to the user.
